// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Badge': string;
  'middle': string;
  'top': string;
}
export const cssExports: CssExports;
export default cssExports;
