// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'border': string;
  'borderBottom': string;
  'borderColorDarkGray': string;
  'borderColorLightGray': string;
  'borderColorRed': string;
  'borderColorTranslucidGray': string;
  'borderLeft': string;
  'borderRight': string;
  'borderTop': string;
  'circle': string;
  'noBorder': string;
  'pill': string;
  'rounding0': string;
  'rounding1': string;
  'rounding2': string;
  'rounding3': string;
  'rounding4': string;
  'rounding5': string;
  'rounding6': string;
  'rounding7': string;
  'rounding8': string;
  'sizeLg': string;
  'sizeSm': string;
  'solid': string;
}
export const cssExports: CssExports;
export default cssExports;
