// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'block': string;
  'blue': string;
  'button': string;
  'disabled': string;
  'enabled': string;
  'gray': string;
  'inline': string;
  'lg': string;
  'md': string;
  'red': string;
  'selected': string;
  'sm': string;
  'solid': string;
  'transparent': string;
  'white': string;
}
export const cssExports: CssExports;
export default cssExports;
