// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'animateIn': string;
  'card': string;
  'hover': string;
}
export const cssExports: CssExports;
export default cssExports;
