// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'border': string;
  'borderDarkGray': string;
  'borderError': string;
  'borderHovered': string;
  'borderRadiusMd': string;
  'borderRadiusSm': string;
  'check': string;
  'checkFocused': string;
  'input': string;
  'inputEnabled': string;
  'sizeMd': string;
  'sizeSm': string;
}
export const cssExports: CssExports;
export default cssExports;
