// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'caret': string;
  'container': string;
  'contents': string;
  'innerContents': string;
  'maxDimensions': string;
  'minDimensions': string;
}
export const cssExports: CssExports;
export default cssExports;
