// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Heading': string;
  'fontSize1': string;
  'fontSize2': string;
  'fontSize3': string;
}
export const cssExports: CssExports;
export default cssExports;
