// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'icon': string;
  'iconBlock': string;
  'rtlSupport': string;
}
export const cssExports: CssExports;
export default cssExports;
