// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Mask': string;
  'wash': string;
  'willChangeTransform': string;
}
export const cssExports: CssExports;
export default cssExports;
