// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Masonry': string;
  'Masonry__Item': string;
  'Masonry__Item__Mounted': string;
}
export const cssExports: CssExports;
export default cssExports;
