// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'AppearAnimation': string;
  'PulseAnimation': string;
  'innerCircle': string;
  'outerCircle': string;
}
export const cssExports: CssExports;
export default cssExports;
