// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'BgDisabled': string;
  'BgEnabled': string;
  'Border': string;
  'BorderCheckedMd': string;
  'BorderCheckedSm': string;
  'BorderDarkGray': string;
  'BorderHovered': string;
  'BorderUnchecked': string;
  'Input': string;
  'InputEnabled': string;
  'RadioButton': string;
  'RadioButtonIsFocused': string;
  'SizeMd': string;
  'SizeSm': string;
}
export const cssExports: CssExports;
export default cssExports;
