// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'SegmentedControl': string;
  'item': string;
  'itemIsNotSelected': string;
  'itemIsSelected': string;
}
export const cssExports: CssExports;
export default cssExports;
