// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'delay': string;
  'icon': string;
  'spin': string;
}
export const cssExports: CssExports;
export default cssExports;
