// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkbox': string;
  'checkboxEnabled': string;
  'focused': string;
  'slider': string;
  'sliderDark': string;
  'sliderLeft': string;
  'sliderLight': string;
  'sliderRight': string;
  'switch': string;
  'switchDarkGray': string;
  'switchGray': string;
  'switchLightGray': string;
  'switchWhite': string;
}
export const cssExports: CssExports;
export default cssExports;
