// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Tabs': string;
  'tab': string;
  'tabIsActive': string;
  'tabIsNotActive': string;
}
export const cssExports: CssExports;
export default cssExports;
