// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'copy': string;
  'fullHeight': string;
  'fullWidth': string;
  'grab': string;
  'grabbing': string;
  'move': string;
  'noDrop': string;
  'pointer': string;
  'touchable': string;
  'zoomIn': string;
  'zoomOut': string;
}
export const cssExports: CssExports;
export default cssExports;
