// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alignCenter': string;
  'alignJustify': string;
  'alignLeft': string;
  'alignRight': string;
  'antialiased': string;
  'breakWord': string;
  'fontStyleItalic': string;
  'fontStyleRegular': string;
  'fontWeightBold': string;
  'fontWeightNormal': string;
  'leadingShort': string;
  'leadingTall': string;
  'noUnderline': string;
  'sansSerif': string;
  'truncate': string;
  'underline': string;
}
export const cssExports: CssExports;
export default cssExports;
