// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'controls': string;
  'player': string;
  'playhead': string;
  'video': string;
}
export const cssExports: CssExports;
export default cssExports;
