// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'base': string;
  'disabled': string;
  'enabled': string;
  'errored': string;
  'normal': string;
}
export const cssExports: CssExports;
export default cssExports;
