// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contain': string;
  'cover': string;
  'img': string;
  'scaled-img': string;
}
export const cssExports: CssExports;
export default cssExports;
